### PR TITLE
Add summary to each program run

### PR DESCRIPTION
**Pull request by bregman-arie**
Print summary of cleaned up resources

### CODE REVIEW

**Comment by bregman-arie** [comment]
Any idea what is the issue with python3?

**Comment by yazug** [comment]
Travis CI failing

**Comment by bregman-arie** [comment]
yes, but why? o0

**Comment by yazug** [comment]
No clue will have to try it locally with python3

**Comment by bregman-arie** [comment]
tested it. locally it works fine.

**Pull request merged**
