### PR TITLE
Switch from print statements to logging library

### PR DESCRIPTION
**Pull request by bregman-arie**
Logging library holds several advantages compared to simple
print statements.

### CODE REVIEW

**Comment by yazug** [comment]
Looks OK I want to test this locally to see behaviour

**Comment by yazug** [comment]
Not Merging as is.  This patch removes the usefulness of the CLI.  

./shale_janitor/janitor.py --cloud=XXX 
no longer shows any details about what could be cleaned up.  This was intended behavior.

Things I would like to see preserved:
    Way to see resources that were identified selected.
    Way to see resources that are identified by --old
    Way to see the manual commands to run to cleanup yourself

**Comment by bregman-arie** [comment]
@yazug "no longer shows any details about what could be cleaned up" - actually it is, but with the right invocation.

I asked people what they thing about the previous output and almost all of them told me "too much output, I don't really care about each command executed".

If someone is interested in such information he or she can use --debug

**Comment by yazug** [comment]
Branch merged manually.  I'm not dropping the pprint or changing logging levels at the same time we change how things are output/logged.  that can be a separate patch to adjust verbosity

**Pull request closed without merging**
